apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-05-20T16:39:28Z"
  generation: 2
  labels:
    name: vue
  name: vue
  namespace: default
  resourceVersion: "7286"
  uid: ee180cb4-2fd8-4e88-b815-5212bac818fb
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-05-20T16:41:06Z"
      creationTimestamp: null
      labels:
        app: vue
    spec:
      containers:
      - image: jkiskis123/vue-kubernetes:latest
        imagePullPolicy: Always
        name: vue
        resources:
          limits:
            cpu: 100m
            memory: 500M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-20T16:41:41Z"
    lastUpdateTime: "2022-05-20T16:41:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
